@startuml
namespace api #LightYellow {
    entity CYS_hashes {
        CYS_hash_sha256_setup
        CYS_hash_sha256_update
        CYS_hash_sha256_finish
    }
    entity CYS_ecc {
        CYS_PROT_ecc_p256_generate
        CYS_PROT_ecc_p256_seal
        CYS_PROT_ecc_p256_derive
        CYS_PROT_ecc_p256_sign
        CYS_ecc_p256_generate
        CYS_ecc_p256_sign
        CYS_ecc_p256_verify
    }
    entity CYS_cipher {
        CYS_cipher_aes_128_import_key
        CYS_cipher_aes_128_ecb
    }
}

namespace api {
    entity CYS_random {
        CYS_random_generate
    }
}

namespace entry #LightYellow {
    entity Entry {
        tee_secure_entry
    }

    entity Operations {
        tee_operation_table
    }
}

api.CYS_hashes ---> Entry::tee_secure_entry
api.CYS_ecc ---> Entry::tee_secure_entry
api.CYS_cipher ---> Entry::tee_secure_entry

api.CYS_random ---> Entry::tee_secure_entry

Entry --> Operations

namespace CryptoService #LightBlue{
    entity sram_puf {
        puf_generate
        puf_init
    }

    entity riot_hashes {
        sha256_setup
        sha256_update
        sha256_finish
    }

    entity riot_cipher {
        cipher_encrypt_ocb
        cipher_decrypt_ocb
    }

    entity riot_random {
        random_init
        random_init_by_array
        random_bytes
    }

    entity micro_ecc {
        uECC_make_key
        uECC_shared_secret
        uECC_sign
        uECC_sign_deterministic
        uECC_verify
    }
}

namespace src #LightYellow {}

namespace src.crypto {
    entity tee_hashes {
        tee_hash_sha256_setup
        tee_hash_sha256_update
        tee_hash_sha256_finish
    }
    entity tee_ecc {
        tee_prot_ecc_p256_generate
        tee_prot_ecc_p256_seal
        tee_prot_ecc_p256_derive
        tee_prot_ecc_p256_sign
        tee_ecc_p256_generate
        tee_ecc_p256_derive
        tee_ecc_p256_sign
        tee_ecc_p256_verify
    }
    entity tee_cipher {
        tee_aes_128_import_key
        tee_aes_128_ecb
    }
}

namespace src.rot {
    entity tee_rot {
        rot_try_generate_aes_key
        rot_try_generate_ecc_p256_key
        rot_encrypt_key_ocb
        rot_decrypt_key_ocb
        rot_sign
        rot_export_public_key
    }
}

namespace src.random {
    entity tee_random {
        tee_random_generate
    }
}

' namespace src.oberon {

' }

Operations ---> src.crypto.tee_hashes
Operations ---> src.crypto.tee_ecc
Operations ---> src.crypto.tee_cipher

' src.crypto.tee_cipher ---> src.rot.tee_rot
src.crypto.tee_ecc ---> src.rot.tee_rot
src.crypto.tee_ecc ---> CryptoService.micro_ecc
src.crypto.tee_ecc ---> CryptoService.riot_random
src.crypto.tee_hashes ---> CryptoService.riot_hashes
src.crypto.tee_cipher ---> CryptoService.riot_cipher
src.random.tee_random ---> CryptoService.riot_random
src.rot.tee_rot ---> CryptoService.riot_random
src.rot.tee_rot ---> CryptoService.riot_cipher
' src.crypto --> src.oberon

@enduml
